spring:
  profiles:
    active:
      - jwt
      - oauth

  application:
    name: auth-BE

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: ${SWAGGER_PATH:/}

  datasource:
    url: ${DB_URL:jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC

  jackson:
    time-zone: UTC

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  time:
    default-zone: ${APP_DEFAULT_ZONE:Asia/Seoul} # 환경변수 APP_DEFAULT_ZONE이 있으면 그걸 쓰고, 없으면 Asia/Seoul
  cookie:
    secure: ${APP_COOKIE_SECURE:false} # 개발환경: false, 프로덕션: true (HTTPS)
    same-site: ${APP_COOKIE_SAME_SITE:Strict} # CSRF 방지: Strict/Lax/None

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.orm.jpa: debug
    org.springframework.boot.autoconfigure.orm.jpa: debug